name: mobile_task_app
description: A mobile task assignment application with GPS-based completion verification.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP and API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # GPS and Location
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.18.1
  uuid: ^4.0.0
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2

  # Authentication
  flutter_secure_storage: ^9.0.0

  # UI Enhancement
  flutter_staggered_animations: ^1.1.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
